#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
# ETH PHY Demo 
# customized for 
# Olimex ESP EVB-REV B LAN8710 CAN IoT Board
# 2017 June 15
# rudi ;-)

PROJECT_NAME := ethernet_demo

include $(IDF_PATH)/make/project.mk

